### ISSUE TITLE
provide building/installation instructions and/or binary release

### ISSUE THREAD

**Issue by VladimirAlexiev** [LdBeth/tree-sitter-rnc#2]
Following your comment in https://github.com/TreeRex/rnc-mode/issues/8, I'd like to give this a try.
- I got `emacs/rnc-ts-mode.el` and tried to compile but it required `treesit`.
- I didn't find `treesit` with list-packages but I found this:
`treesit-auto` 20231211.1229  incompat     melpa    Automatically use tree-sitter enhanced major modes
- However, it complained `Package ‘emacs-29.0’ is unavailable.` (I got emacs 28.1)
- Also, I see a C file `parse.c`. I have `gcc` so may be able to compile it.

Please add installation instructions and required dependencies to the README.
Thanks and have a great New Year!

**Comment by LdBeth** [comment]
>>>>> In ***@***.***> 
>>>>>	Vladimir Alexiev ***@***.***> wrote:
>
> * I didn't find treesit with list-packages but I found this:
>  treesit-auto 20231211.1229 incompat melpa Automatically use tree-sitter enhanced
>  major modes
> * However, it complained Package ‘emacs-29.0’ is unavailable. (I got emacs 28.1)
> * Also, I see a C file parse.c. I have gcc so may be able to compile it.

Hello, this package requires Emacs 29 compiled with tree-sitter
library where `treesit' is builtin in 29.  I assume you are using
Linux so the details on how to compile Emacs with tree-sitter on Linux
can be find at
https://www.masteringemacs.org/article/how-to-get-started-tree-sitter

I believe there is no way to use this package with Emacs 28.

After that, in the top of `tree-sitter-rnc' directory, compile the binary
is as simple as run

$ cc -fPIC -c -Isrc src/parser.c
$ cc -fPIC -shared parser.o -o libtree-sitter-rnc.so

Or if you know how to use Makefile, edit the

LIBEXT := dylib

line to

LIBEXT := so

and run

$ make

(If you are using macOS then just directly make)

Copy the result (libtree-sitter-rnc.so for example)
to ~/.emacs.d/tree-sitter as described in the
how-to-get-started-tree-sitter link,

Also copy emacs/rnc-ts-mode.el to somewhere you know emacs can find it,
byte-compile (optional) and load it the usually way you do it.

**Comment by LdBeth** [comment]
> I believe there is no way to use this package with Emacs 28.

There is an external package https://emacs-tree-sitter.github.io that
supports Emacs 28 and the shared library can be used with them, but
the Emacs Lisp mode is incompatible and I have no plan on doing a
port.

A brief instruction on how to install is now provided with README, and
I have uploaded Linux/macOS x86_64 shared library file but I have no
access to other platform (maybe also x_86_64 NetBSD but I doubt anyone
else would need that).

I hope you'll find these helpful
